Feature/157864407
grupotesseract/fabiao pull request #18
Opened 2018-09-21 19:03 UTC by denisakira

Requerimentos para a API do PagSeguro:

'cep',
'endereco',
'numero',
'bairro',
'cidade',
'estado',
'email',
'nome',
'cpf',
'nascimento'

2018-09-21 19:27 UTC, ltgouvea requested changes
Mano, testei o merge localmente por aqui e seguem algumas sugestões
1 - Remover o ícone do link para a datatable de clientes no menu da sidebar.
2 - Traduzir essa mesma datatable e deixar apenas os botões Adicionar/Atualizar (Create/Reload) assim como está customizado nas demais datatables. 
3 - A view de criar/atualizar clientes está sem campos, apenas com o botão salvar; isso é intencional? Creio que o Beto eventualmente terá de editar ou criar manualmente alguém por ali. Qualquer dúvida pra implementar isso posso te ajudar, mas creio que com o generator já seja tranquilo reescrever essa view.
CC: @fernandesfernando

2018-09-21 22:01 UTC, denisakira commented
Valeu pelas sugestões, fiz as mudanças. Dá uma olhada quando der, bro.

2018-09-21 23:45 UTC, ltgouvea commented
Corrigi algumas coisinhas minor e LGTM :smile:.
Assim que o Atchim tmb puder dar uma testada, mergeamos. Valeu mano!

2018-09-26 16:51 UTC, ltgouvea approved these changes

2018-10-10 22:20 UTC, merged